name: Build and Push Docker Image

on:
  push:
    branches: [ main, develop ] # <-- Added develop here

permissions:
  contents: read
  packages: write  # This is the line that fixes the "Denied" error

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Python Code
        uses: actions/checkout@v3

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      # REQUIRED FOR CACHING: This enables the advanced Docker engine
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Dynamically tags as 'latest' if on main, otherwise tags as 'staging'
          tags: |
            ghcr.io/mpylon16/congregational-key-finder:${{ github.ref == 'refs/heads/main' && 'latest' || 'staging' }}
          # THE SPEED FIX: Tells GitHub to save/load the Docker layer cache
          cache-from: type=gha
          cache-to: type=gha,mode=max